server:
  port: 9600
  servlet:
    context-path: /swagger-example
spring:
  rabbitmq:
    addresses: 192.168.32.168
    port: 5672
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
    username: admin
  redis:
    host: 127.0.0.1
    port: 6379
sw:
  swagger:
    enable: true
    title: sw框架测试
    contact:
      name: syw
      email: 17637148310@163.com
    version: 1.0-SNAPSHOT
    base-package: com.sw
  oss:
    #minio形式
    minio:
      endpoint: http://127.0.0.1:5200
      default-bucket-name: minio
      secret-key: minio
      access-key: minio
  security:
    ignore-path: /sa-token/login
    enable-security-filter: true